version: "3.4"

services:
  showmecrypto:
    image: showmecrypto
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 80:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
